[package]

name = "isosurface-extraction"
version = "0.0.0"
authors = [
  "Zeke Foppa <benjamin.foppa@gmail.com>",
]

[lib]
name = "isosurface_extraction"
path = "./src/mod.rs"

[dependencies]
cgmath = "0.15"
log    = "*"

[dependencies.voxel-data]
git = "https://github.com/bfops/rust-voxel-data"
